## It contains all the configs required in the project
data:
  local_dir: data
  train_images_dir: data/train_images.npy
  train_labels_dir: data/train_labels.npy
  test_images_dir: data/test_images.npy
  test_labels_dir: data/test_labels.npy


