## It contains all the configs required in the project
data:
  local_dir: data
  train_images_dir: data/train_images.npy
  train_labels_dir: data/train_labels.npy
  test_images_dir: data/test_images.npy
  test_labels_dir: data/test_labels.npy


params:
  img_shape: [180,180,3]
  lr: 0.001
  loss: sparse_categorical_crossentropy
  metrics: ["accuracy"]
  validation_split: 0.2
  seed: 42
  batch_size: 32
  buffer_size: 32
  epochs: 01